CREATE TABLE IF NOT EXISTS TASKS (
	id LONG PRIMARY KEY,
	user_name VARCHAR(255) NOT NULL,
	description VARCHAR(4000),
	is_completed BOOLEAN,
	shared_users VARCHAR(4000)
);

CREATE SEQUENCE IF NOT EXISTS TASKS_SEQ_ID;